USE db_altn72_hope;

INSERT INTO StudentTool (toolID, title, domainName, detailedDesc, link, accessInstruction)
VALUES
(1,
 'GitHub Global Campus (GitHub Education)',
 'Bouquet de services',
 'Sélection d\'outils et de services pour booster votre productivité en tant qu\'élève-ingénieur du numérique. Le GitHub Student Developer Pack vous donne un accès gratuit à un impressionnant catalogue de services et d\'outils. Ex: GitHub pro, GitHub Copilot, DigitalOcean, Outils JetBrains (IntelliJ IDEA Ultimate, PyCharm,...), Azure, Heroku, etc... Une courte vidéo de présentation est disponible ici : https://www.youtube.com/watch?v=HIVFdN9VGgw',
 'https://education.github.com/discount_requests/application',
 'a) Aller sur le lien indiqué\nb) Remplir les différents champs sur la page\nc) Choisir \'French School of Electronics and Computer Science\' pour l\'école\nd) Envoyer un justificatif (idéalement la carte d\'étudiant)\ne) Attendre la validation par l\'équipe de GitHub\nf) Profiter des différentes offres incluses dans le programme'
),
(2,
 'Coding Rooms',
 'Codage / Développement',
 'Exercices pratiques de programmation, en ligne',
 'https://www.codingrooms.com/',
 'L\'enseignant partage un lien d\'invitation unique pour rejoindre son espace de cours sur la plateforme Coding Rooms.\nOn peut ensuite accéder aux exercices et aux ressources du cours.'
),
(3,
 'Nowledgeable',
 'Codage / Développement',
 'Exercices pratiques de programmation, en ligne',
 'https://nowledgeable.com/',
 'a) Allez sur : https://nowledgeable.com/login\nb) Saisissez votre adresse mail EFREI\nc) Un lien vous sera envoyé pour créer et activer un compte'
),
(4,
 'Jupyter notebook',
 'Codage / Développement',
 'Jupyter Notebook est une application web qui vous permet de stocker des lignes de code Python, les résultats de l’exécution de ces dernières (graphiques, tableaux, etc.) et du texte formaté. Il permet donc de combiner code, visualisations et explications dans un même document, ce qui facilite l\'exploration et le partage de données.',
 'https://jupyter.org/',
 'OPTION A\na) Installer PyCharm Pro\nb) Ouvrir le notebook à partir de l\'IDE.\n\nOPTION B\nInitialiser un notebook depuis Google Colab\n\nOPTION C\na) Installer Anaconda (gratuit)\nb) Lancer le notebook Jupyter via le lien présent dans le navigateur Anaconda'
),
(5,
 'repl.it',
 'Codage / Développement',
 'Exercices pratiques de programmation (notamment de programmation fonctionnelle) en ligne ou via une app',
 'https://replit.com/',
 'a) Créer un compte (option gratuite)\nb) Vous aurez alors accès à la plateforme et à l\'ensemble de ses services'
),
(6,
 'Google Colaboratory (Colab)',
 'Codage / Développement',
 'Colab est une plateforme très pratique pour exécuter du code Python sans avoir besoin d\'installer Python localement. Elle est souvent utilisée pour les démonstrations, les TP et les projets en Machine Learning car elle donne accès à des ressources de calcul gratuites (CPU, GPU, TPU).',
 'https://colab.research.google.com/?hl=fr',
 'a) Se connecter à Colab avec son compte Google\nb) Créer un nouveau notebook\nc) Commencer à coder en Python directement dans le navigateur.'
),
(7,
 'Environnements virtuels',
 'Hyperviseurs',
 'Machines virtuelles',
 'https://moodle.myefrei.fr/course/view.php?id=6460',
 'OPTION I : Utilisation d\'un hyperviseur\na) Installer VirtualBox ou VMWare\nb) Télécharger un fichier image *.iso\nc) L\'ouvrir dans l\'hyperviseur\n\nOPTION II : Utilisation de Vagrant\na) Installer Vagrant (gratuit)\nb) Créer sa VM en passant par une box de Vagrant'
),
(8,
 'Environnements virtuels',
 'Containers',
 'Containers Docker',
 'https://www.docker.com/',
 'a) Installer Docker\nb) Aller sur le Docker Hub pour récupérer une ou des image(s) Docker correspondant au(x) besoin(s)\nc) Créer un ou des container(s) à partir de cette/ces image(s)'
),
(9,
 'TryHackme',
 'Cyber sécurité',
 'TryHackMe est une excellente ressource pour se former à la cybersécurité de manière pratique. Les exercices, souvent présentés sous forme de scénarios réalistes, permettent d\'apprendre en s\'amusant. Des challenges concrets permettent de pratiquer de façon ludique.  #cyber #hacking',
 'https://tryhackme.com/',
 'a) Aller sur le site https://tryhackme.com/\nb) Cliquer sur connexio\nc) Entrer vos identifiants\nd) Commencer à travailler\n\nRemarque : Il y a 3 plans correspondant à 3 tarifs différents. Le plan gratuit devrait convenir pour la plupart des cours.'
),
(10,
 'Hack The Box',
 'Cyber sécurité',
 'Hack The Box est une plateforme de cybersécurité réputée pour ses challenges de type "capture de drapeaux" (CTF). Elle propose des machines virtuelles à attaquer légalement pour s\'entraîner au hacking éthique.',
 'https://www.hackthebox.com/',
 'Créer un compte standard sur le site via le lien indiqué'
),
(11,
 'AWS',
 'Cloud provider',
 'Fournisseur Cloud',
 'https://signin.aws.amazon.com/signup?request_type=register',
 '?'
),
(12,
 'AWS Academy',
 'Formations en ligne',
 'Plateforme d\'AWS de formations en ligne',
 'https://aws.amazon.com/fr/training/awsacademy/',
 '?'
),
(13,
 'Azure',
 'Cloud provider',
 'Fournisseur Cloud',
 'https://azure.microsoft.com/en-us',
 '?'
),
(14,
 'Integral Calculator',
 'Mathématiques',
 'Calcul d\'intégrales en ligne',
 'https://www.integral-calculator.com/',
 '?'
),
(15,
 'eMathHelp',
 'Mathématiques',
 'Résolution de problèmes mathématiques, étape par étape',
 'https://www.emathhelp.net/en/',
 '?'
),
(16,
 'MultisimLive',
 'Electronique',
 'Simulation de programmation de cartes electroniques',
 'https://www.multisim.com/',
 '?'
),
(17,
 'MATLAB & Simulink (MathWorks)',
 'Mathématiques',
 'Calcul numérique / Analyse de données',
 'https://fr.mathworks.com/products/matlab/student.html',
 'Un accompagnement clair et détaillé est proposé dans les cours utilsant l\'outil'
),
(18,
 'Patchwork3D & AccelVR (Lumiscaphe)',
 'Réalité virtuelle / augmentée',
 'Modélisation 3D / Rendu RV',
 'https://resources.lumiscaphe.com/Software_Suite/2023/en/accel-vr.html <br>https://resources.lumiscaphe.com/Software_Suite/2023/en/patchwork-3d.html',
 'S\'informer auprès de l\'enseignant'
),
(19,
 'Kaggle',
 'Data Science',
 'Kaggle est une plateforme web qui fournit des outils et des ressources puissants pour aider à progresser en Data Science. Vous trouverez plus de 50 000 jeux de données publics et 400 000 notebooks publics disponibles pour tous.',
 'https://www.kaggle.com/',
 'S\'informer auprès de l\'enseignant'
),
(20,
 'Notion',
 'Gestion de projets et collaboration',
 'Notion est une application/plateforme de prise de notes, de gestion de projet et de collaboration. Notion est conçu pour permettre aux utilisateurs d\'organiser leurs informations de manière flexible, en utilisant une variété de formats tels que des notes, des bases de données relationnelles, des listes de tâches, des calendriers et des tableaux, le tout dans un seul espace de travail intégré.',
 'https://www.notion.so/fr-fr',
 'S\'informer auprès de l\'enseignant'
),
(21,
 'Trello',
 'Gestion de projets et collaboration',
 'Trello est une plateforme de gestion de projet très visuelle et intuitive. Elle est idéale pour les travaux de groupe, car elle permet de suivre facilement l\'avancement des tâches et de communiquer efficacement entre les membres de l\'équipe.',
 'https://trello.com/home',
 'a) Créer un compte (version gratuite)\nb) Créer un espace puis un premier tableau\nc) Commencer à utiliser la plateforme'
),
(22,
 'Code Ocean',
 'Data Science',
 'Code Ocean une plateforme centralisée pour la création, le partage, la publication, la préservation et la réutilisation de code et de données exécutables. Avec Code Ocean, les chercheurs peuvent facilement analyser, organiser et exécuter des travaux de recherche et les publier dans des dépôts et des revues.',
 'https://codeocean.com/',
 'S\'informer auprès de l\'enseignant'
),
(23,
 'Marp',
 'Génération de documents',
 'Création de slides à prtir de documents Markdown',
 'https://marp.app/',
 'La documentation sur le site officiel est très détaillée et suffisamment précise pour permettre une prise en main autonome'
),
(24,
 'LaTeX',
 'Génération de documents',
 'LaTeX est un langage et un système de composition de documents',
 'https://www.latex-project.org/',
 'La documentation sur le site officiel est très détaillée et suffisamment précise pour permettre une prise en main autonome'
),
(25,
 'Material for mkdocs',
 'Génération de documents',
 'Création de documentation (de code)',
 'https://squidfunk.github.io/mkdocs-material/',
 'La documentation sur le site officiel est très détaillée et suffisamment précise pour permettre une prise en main autonome'
),
(26,
 'Looping',
 'Bases de données',
 'Modélisation conceptuelle de données',
 'https://www.looping-mcd.fr/',
 'Télécharger et installer'
),
(27,
 'MongoDB Compass',
 'Bases de données',
 'GUI pour MongoDB',
 'https://www.mongodb.com/products/tools/compass',
 'Télécharger et installer'
),
(28,
 'Wireshark',
 'Réseaux',
 'Wireshark est un analyseur de paquets libre et gratuit. Il est notamment utilisé dans le dépannage et l’analyse de réseaux informatiques et le développement de protocoles.',
 'https://www.wireshark.org/',
 'Télécharger et installer'
);

INSERT INTO UserApp (userID, username, password, email, role)
VALUES
(1, 'admin', 'Azerty0', 'admin@gmail.com', 'ADMIN'),
(2, 'student', 'Azerty0', 'student@school.com', 'STUDENT'),
(3, 'teacher', 'Azerty0', 'teacher@school.com', 'TEACHER');